[project]
name = "plain-abc"
version = "0.1.0"
authors = [{ name = "Chielo Newctle", email = "ChieloNewctle@gmail.com" }]
description = "An ABC implementation without metaclass"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ChieloNewctle/plain-abc"
"Bug Tracker" = "https://github.com/ChieloNewctle/plain-abc/issues"

[project.optional-dependencies]
tests = ["pytest"]
