[project]
name = "plain-abc"
version = "0.1.1"
authors = [{ name = "Chielo", email = "mail@chielo.org" }]
description = "An ABC implementation without metaclass"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ChieloNewctle/plain-abc"
"Bug Tracker" = "https://github.com/ChieloNewctle/plain-abc/issues"

[project.optional-dependencies]
tests = ["pytest"]
